services:

  backend:

    build: .

    container_name: quantum-backend

    restart: always

    ports:
      - "8000:8000"

    env_file:
      - .env

    depends_on:
      - postgres

    volumes:
      - .:/app

  postgres:

    image: postgres:16

    container_name: quantum-postgres

    restart: always

    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: quantumlabs

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: